services:
  web:
    build:
      context: ./frontend
      target: builder
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    command: pnpm start
    volumes: []
    environment:
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
