"""initial_schema

Revision ID: 70ed8711aca8
Revises: 
Create Date: 2026-03-19 08:53:30.664242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ed8711aca8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('article_ref', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('evidence_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_framework'), 'controls', ['framework'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'assessor', 'risk_manager', 'executive', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_systems',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('risk_tier', sa.Enum('unacceptable', 'high', 'limited', 'minimal', name='risktier'), nullable=False),
    sa.Column('business_unit', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'decommissioned', 'draft', name='systemstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=False),
    sa.Column('assessor_id', sa.String(), nullable=False),
    sa.Column('frameworks', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'complete', name='assessmentstatus'), nullable=False),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_controls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('control_id', sa.String(), nullable=False),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('is_compliant', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_controls_assessment_id'), 'assessment_controls', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_controls_control_id'), 'assessment_controls', ['control_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('control_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('collected', 'stale', 'missing', name='evidencestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('control_id', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('remediation_task', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='findingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_assessment_controls_control_id'), table_name='assessment_controls')
    op.drop_index(op.f('ix_assessment_controls_assessment_id'), table_name='assessment_controls')
    op.drop_table('assessment_controls')
    op.drop_table('assessments')
    op.drop_table('ai_systems')
    op.drop_table('users')
    op.drop_index(op.f('ix_controls_framework'), table_name='controls')
    op.drop_table('controls')
    # ### end Alembic commands ###
