apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compass.fullname" . }}-secrets
  labels:
    {{- include "compass.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  DATABASE_URL: {{ include "compass.databaseUrl" . | quote }}
  REDIS_URL: {{ include "compass.redisUrl" . | quote }}
