apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "compass.fullname" . }}-web
  labels:
    {{- include "compass.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.registry }}/{{ .Values.web.image }}:{{ .Values.web.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.port }}
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://{{ include "compass.fullname" . }}-api:{{ .Values.api.port }}"
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
