apiVersion: v1
kind: Service
metadata:
  name: {{ include "compass.fullname" . }}-web
  labels:
    {{- include "compass.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
